AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - lib/**/*
    - node_modules/**/*
    - Guardfile

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - config/**/*

Metrics/AbcSize:
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - db/**/*
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/**/*